name: publish latest

on:
  release:
    types: [released]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: echo ::set-env name=REPO_NAME::${{ github.event.repository.name }}
      - run: npx @angular/cli@6.2.9 new build --skip-tests --minimal --routing --skip-git
      - run: cd build
      - run: npm run ng -- generate library angular --create-application=false --skip-git --skip-tests --inline-style
      - run: rm -rf projects/angular
      - run: git clone https://github.com/themost-framework/angular.git projects/angular
      - run: cd projects/angular
      - run: npm i npm-install-peers --no-save
      - run: ./node_modules/.bin/npm-install-peers
      - run: cd ../..
      - run: npm run ng build angular
      - run: cd dist/angular
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
